name: cumulonimbus
version: 1.23.1
summary: Cumulonimbus - A simple, beautiful podcast app.
description: |
  Cumulonimbus is very much a work in progress. Please expect bugs.
grade: stable
confinement: strict

parts:
  cumulonimbus:
    plugin: dump
    source: https://github.com/z-------------/cumulonimbus/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Cumulonimbus_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    after:
      - desktop-gtk2
    # Clear the execstack
    # https://forum.snapcraft.io/t/snap-and-executable-stacks/1812
    prepare: |
        execstack --clear-execstack opt/Cumulonimbus/cumulonimbus
    build-packages:
      - execstack
    stage-packages:
      - libasound2
      - libgconf2-4
      - libgl1-mesa-glx
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  cumulonimbus:
    command: bin/desktop-launch $SNAP/opt/Cumulonimbus/cumulonimbus
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - bluez
      - browser-support
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
